name: Publish
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: write
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Read version from deno.json
        id: get_version
        run: |
          VERSION=$(cat deno.json | jq -r '.version')
          echo "version=$VERSION" >> $GITHUB_ENV

      - name: Publish package
        run: deno publish

      - name: Create GitHub Tag
        uses: actions/github-script@v7
        with:
          script: |
            const tag = process.env.version;
            const latestCommitSha = context.sha;  
            await github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/${tag}`,
              sha: latestCommitSha,
            });
            core.setOutput('tag', tag);

      - name: Create GitHub Release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          release_name: Release ${{ steps.get_version.outputs.version }}
          body: |
            Automatically generated release for version ${{ steps.get_version.outputs.version }}
          draft: false
          prerelease: false
